# Generated by Django 5.0.2 on 2024-02-14 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=90)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.state')),
            ],
        ),
    ]
