# Generated by Django 5.0.2 on 2024-02-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_enquirysource'),
    ]

    operations = [
        migrations.CreateModel(
            name='followupstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followupstatus', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=90)),
            ],
        ),
    ]
