# Generated by Django 5.0.2 on 2024-02-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_batch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='batch',
            new_name='branch',
        ),
    ]
