# Generated by Django 5.0.2 on 2024-02-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_rename_batch_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('company', models.CharField(max_length=90)),
                ('state', models.CharField(max_length=90)),
                ('district', models.CharField(max_length=90)),
                ('qualification', models.CharField(max_length=90)),
                ('course', models.CharField(max_length=90)),
            ],
        ),
    ]
